export { default as Food } from '@/assets/image/food.jpg'
export { default as RestoProfile } from '@/assets/image/resto-profile.jpg'
export { default as Login } from '@/assets/image/login.png'
export { default as Prof } from '@/assets/image/profile.png'
export { default as Menu } from '@/assets/image/menu.jpg'
export { default as Phone } from '@/assets/image/phone.jpg'
