export { default as CardJenisUser } from '@/components/card/CardJenisUser.vue'
export { default as CardMetodeBayar } from '@/components/card/CardMetodeBayar.vue'
export { default as CardPaket } from '@/components/card/CardPaket.vue'
export { default as CardResto } from '@/components/card/CardResto.vue'
export { default as CardNote} from '@/components/card/CardNote.vue'
