export { default as InputPassword } from '@/components/InputPassword.vue'
export { default as InputEmail } from '@/components/InputEmail.vue'

export { default as Header } from '@/components/Header.vue'
export { default as Navigasi } from '@/components/Navigasi.vue'
export { default as NavComponents } from '@/components/NavComponents.vue'
export { default as Resto } from '@/components/Resto.vue'
export { default as InputText } from '@/components/InputText.vue'
export { default as ButtonPrimary } from '@/components/ButtonPrimary.vue'
export { default as LaporanPendapatan } from '@/components/LaporanPendapatan.vue'
export { default as LaporanComponents } from '@/components/LaporanComponents.vue'
export { default as PendapatanComponents } from '@/components/PendapatanComponents.vue'
