// export { default as CommunityIcon } from '@/components/icons/IconCommunity.vue'
// export { default as DocumentationIcon } from '@/components/icons/IconDocumentation.vue'
// export { default as EcosystemIcon } from '@/components/icons/IconEcosystem.vue'
// export { default as SupportIcon } from '@/components/icons/IconSupport.vue'
// export { default as ToolingIcon } from '@/components/icons/IconTooling.vue'
export { default as ErrorIcon } from '@/components/icons/IconError.vue'
export { default as WarningIcon } from '@/components/icons/IconWarning.vue'
export { default as SuccessIcon } from '@/components/icons/IconSuccess.vue'
export {default as EyesOpen} from '@/components/icons/EyesOpen.vue'
export {default as EyesClose} from '@/components/icons/EyesClose.vue'
export {default as IconSearch} from '@/components/icons/IconSearch.vue'
export {default as Dropdown} from '@/components/icons/IconDropdown.vue'
export {default as UserInvalid } from '@/components/icons/IconUserInvalid.vue'
export {default as UserValid } from '@/components/icons/IconUserValid.vue'
export { default as Logo } from '@/components/icons/LogoIcon.vue'
export { default as Profil } from '@/components/icons/ProfilIcon.vue'
export { default as HomeIcon } from '@/components/icons/HomeIcon.vue'
export { default as LaporanIcon } from '@/components/icons/LaporanIcon.vue'
export { default as UpgradeIcon } from '@/components/icons/UpgradeIcon.vue'
export { default as NotesIcon } from '@/components/icons/NotesIcon.vue'
export { default as HomeClick } from '@/components/icons/HomeClick.vue'
export { default as LaporanClick } from '@/components/icons/LaporanClick.vue'
export { default as UpgradeClick } from '@/components/icons/UpgradeClick.vue'
export { default as NotesClick } from '@/components/icons/NotesClick.vue'
export { default as ChevronRight } from '@/components/icons/ChevronRightIcon.vue'

// export { default as CommunityIcon } from '@/components/icons/IconCommunity.vue'
// export { default as DocumentationIcon } from '@/components/icons/IconDocumentation.vue'
// export { default as EcosystemIcon } from '@/components/icons/IconEcosystem.vue'
// export { default as SupportIcon } from '@/components/icons/IconSupport.vue'
// export { default as ToolingIcon } from '@/components/icons/IconTooling.vue'
// export { default as ErrorIcon } from '@/components/icons/IconError.vue'
// export { default as WarningIcon } from '@/components/icons/IconWarning.vue'
// export { default as SuccessIcon } from '@/components/icons/IconSuccess.vue'
